$(document).ready(function() {
	$("#q1").click(function(){
		$("#a1").css("visibility": "visible");
	});
	$("#q2").click(function(){
		$("#a2").toggle();
	});
	$("#q3").click(function(){
			$("#a3").toggle();
	});
	$("#q4").click(function(){
			$("#a4").toggle();
	});
	$("#q5").click(function(){
			$("#a5").toggle();
	});
	$("#q6").click(function(){
			$("#a6").toggle();
	});
	$("#q7").click(function(){
			$("#a7").toggle();
	});
	$("#q8").click(function(){
			$("#a8").toggle();
	});
	$("#q9").click(function(){
			$("#a9").toggle();
	});
	$("#q10").click(function(){
			$("#a10").toggle();
	});
});
