$(document).ready(function() {
	$("#q1").click(function(){
		$("#a1").css();
	});
	$("#q2").click(function(){
		$("#a2").css();
	});
	$("#q3").click(function(){
			$("#a3").css();
	});
	$("#q4").click(function(){
			$("#a4").css();
	});
	$("#q5").click(function(){
			$("#a5").css();
	});
	$("#q6").click(function(){
			$("#a6").css();
	});
	$("#q7").click(function(){
			$("#a7").css();
	});
	$("#q8").click(function(){
			$("#a8").css();
	});
	$("#q9").click(function(){
			$("#a9").css();
	});
	$("#q10").click(function(){
			$("#a10").css();
	});
});
